image: docker:latest

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE
  IMAGE_TAG_CURRENT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  IMAGE_TAG_ANDROID_CURRENT: $CI_REGISTRY_IMAGE:android-$CI_COMMIT_SHA
  IMAGE_TAG_ANDROID_LATEST: $CI_REGISTRY_IMAGE:android-latest

build_ionic:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # - echo "$GITLAB_DEPLOY_SSH_KEY" > luckyzune_cordova_secure_storage_deploy
    # - echo "$GITLAB_DEPLOY_SSH_KEY_PUB" > luckyzune_cordova_secure_storage_deploy.pub
  script:
    - docker build --cache-from $IMAGE_TAG_LATEST -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_TAG_CURRENT
    - docker tag $IMAGE_TAG $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_CURRENT
    - docker push $IMAGE_TAG_LATEST
