language: bash
services: docker

script: 
  - |
    (
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      cd builder && docker build -t luckyzune/ionic:latest .
      docker push luckyzune/ionic:latest
      
      docker tag luckyzune/ionic:latest luckyzune/ionic:9.1.24-builder
      docker push luckyzune/ionic:9.1.24-builder
    )
after_script:
  - docker images